### ISSUE TITLE
GitFileSystemProvider.getInstance() classloader issues

### ISSUE THREAD

**Issue by jendap** [beijunyi/ParallelGit#5]
There is a problem with class loading when used in eclipse with maven project. It does not find instance of `GitFileSystemProvider` because...

`FileSystemProvider.getInstance()` calls `FileSystemProvider.installedProviders()` which eventually calls `ClassLoader.getSystemClassLoader()`

The problem is: it is not the "system" class loader who see the parallelgit-filesystem jar. We can try reason about what is "boot class loader", or "system class loader", what IDEs or web servers are doing with class loading. But it would still be fragile. Can you simply get the singleton instance without calling `FileSystemProvider.getInstance()`? It is not needed, is it?

**Comment by beijunyi** [comment]
I agree with you. Would it solve the problem if I change ```GitFileSystem.getInstance()``` to:

```java
@Nonnull
public static GitFileSystemProvider getInstance() {
  if(INSTANCE == null) {
    for(FileSystemProvider provider : FileSystemProvider.installedProviders()) {
      if(provider instanceof GitFileSystemProvider) {
        INSTANCE = (GitFileSystemProvider) provider;
        break;
      }
    }
    if(INSTANCE == null)
      INSTANCE = new GitFileSystemProvider();
  }
  return INSTANCE;
}
```

Let me know if you have another idea in mind. Cheers

**Comment by beijunyi** [comment]
The problem with using a ```GitFileSystemProvider``` that is not properly installed is that you can't open a new ```GitFileSystem``` from URI e.g.

```java
URI uri = URI.create("gfs:/repo");
GitParams params = GitParams.emptyMap().setBranch("master");
FileSystem gfs = FileSystems.newFileSystem(uri, params)
```

That's why I want to encourage people to have it installed properly, so all features are enabled.

**Comment by jendap** [comment]
Thank you for fixing this! It works on 2.0.0 release.
